config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'welcome/index'
  #root 'welcome#index'
  root 'cats#index'

  #resources :users
  resources :cats do
    resources :comments
  end

  resources :welcome do
    resources :comments
  end

#  resources :admins

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resource :dashboard do
      post :edit_multiple
      put :update_multiple
    end
  end

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  post '/users' => 'users#create'
  post '/:id/edit' => 'users#update'
  #post '/create' => 'users#create'
  post '/signup' => 'users#create'
  mount Like::Engine => '/'

  resources :users, :path => ''


end

app/models/cat.rb
class Cat < ActiveRecord::Base
	belongs_to :user
  has_many :comments

	#def as_json(options={})
		def self.search(search)
			where("name LIKE ?", "%#{search}%")
		end
	#end

  #http://127.0.0.1:3000/cats?search=12

	def self.userList
		# return self.find_by_sql(
		# 		"SELECT * FROM 'users' AS u
		# 		 JOIN 'like_likes' as l ON u.id = l.liker_id
		# 		 WHERE l.liker_id = ('#{self}')"
		# )

		where("id = :id")
	end

	has_attached_file :picture,
									styles: { medium: "300x300#", thumb: "100x100#" },
									:default_url => ActionController::Base.helpers.asset_path("kitty404.jpg")
	validates_attachment_content_type :picture, :content_type => [ 'image/gif', 'image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg' ]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :cat
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :cats

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, length: { minimum: 4, maximum: 50 }, presence: { message: 'should have some words in it' }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  #validates_presence_of :name, presense: true

  # def to_param
  #   name
  # end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
  #belongs_to :cat
  has_many :comments
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_filter lambda { @body_class = 'admin-page' }
	def index
		@users = User.all
		@cats = Cat.all
	end

	def show

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter lambda { @body_class = 'cats-page' }
  helper ApplicationHelper
  ActiveRecord::Base.include_root_in_json = true

  def index
    @cat = Cat.all

    if params[:search]
      @catFind = Cat.search(params[:search]).order("created_at DESC")

    else
      @catFind = Cat.all.order('created_at DESC')
    end
  end

  def show
    @cat = Cat.find(params[:id])
    #puts @cat.inspect
    @cur_user = User.find(params[:id])
    render partial: 'shared/cat'
  end

  def new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.save
    redirect_to @cat
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :text, :user_id, :picture)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @cat = Cat.find(params[:cat_id])
    @comment = @cat.comments.create(comment_params)
    redirect_to cat_path(@cat)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter lambda { @body_class = 'session-page' }
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]
  before_filter lambda { @body_class = 'users-pageRegistration' }
  helper UsersHelper

  def index
    @user = User.all
  end

  def update
    #@user = User.find_by_name(params[:id])
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
    Rails.logger.debug("Id: #{params[:id]}")
    #@user = User.find_by_name(params[:id])
    @user = User.find(params[:id])
  end

  def show
    #@user = User.find_by_name(params[:id])
    @user = User.find(params[:id])
    @users_cats = Cat.all.where('user_id' => @user)
    @users_cats_count = @users_cats.count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = user.id
      redirect_to @user
    else
      #session[:user_id] = nil
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :nickname, :website, :about, :phone, :sex)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter lambda { @body_class = 'main-page' }
  helper WelcomeHelper

  def index
    #@cat = Cat.all
    #@catId = Cat.find_by_name(params[:id])
    #@catId = Cat.find_by_id(params[:id])
    #@user = User.joins(:cats)
    #puts @catId.inspect
    #@comment = @cat.comments.create(comment_params)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def foo_helper
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  end
end

app/helpers/cats_helper.rb
module CatsHelper
  def catId(param)
    ActiveRecord::Base
        .connection
        .execute("SELECT * FROM 'users' AS u
                 JOIN 'like_likes' as l ON u.id = l.liker_id
                 WHERE l.likeable_id = (#{param})")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # def validation_field_for(fieldname)
  #   if @user.errors[":#{fieldname}"]
  #     @user.errors[":#{fieldname}"].join(' ')
  #   end
  # end

  def validation_field_for(fieldname)
    if @user.errors[fieldname]
      @user.errors[fieldname].join(' ')
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def catId(param)
    ActiveRecord::Base
       .connection
       .execute("SELECT * FROM 'users' AS u
                 JOIN 'like_likes' as l ON u.id = l.liker_id
                 WHERE l.likeable_id = (#{param})")
  end
end

app/views/cats/index.html.erb
<% @cat.each do |cat| %>
    <div class="col-md-4">
      <div class="cat" data-href="<%= cat_path(cat) %>">
        <div>catid <%= cat.id %></div>
        <div><%= cat.name %></div>
        <div><%= cat.text %></div>
        <div><%= image_tag cat.picture.url(:thumb) %></div>

        <div>


          <% if Like::Like.with_likeable(cat).count != 0 %>
            <h8>Users like your cat</h8>
            <% catId(cat.id).each do |lu| %>
                <strong><%= lu["name"] %></strong>
            <% end %>
          <% end %>

        </div>

        <div id="like" class="<%= Like::Like.with_likeable(cat).count == 0 ? "notsel" : "sel" %>">
          <% if Like::Like.liking?(current_user, cat) %>
              <%= render 'shared/heart_svg' %>
              <%= link_to 'Like', like_path_for(cat), method: :delete %>
              <%if Like::Like.with_likeable(cat).count != 0%>
                  <%= Like::Like.with_likeable(cat).count %>
              <%end%>
          <% else %>
              <%= render 'shared/heart_svg' %>
              <%= link_to 'Like', like_path_for(cat), method: :post %>
              <%if Like::Like.with_likeable(cat).count != 0%>
                  <%= Like::Like.with_likeable(cat).count %>
              <%end%>
          <% end %>
        </div>



        <a href="<%= user_path(cat.user) %>"><%= cat.user.name %></a>
        <!--<a href="<%= cat_path(cat) %>" class="showCat">show</a>-->
      </div>
    </div>
<% end %>

app/views/cats/new.html.erb
<div class="col-md-12">
  <%= form_for :cat, url: cats_path do |f| %>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :text %><br>
        <%= f.text_area :text %>
      </p>

        <%= f.file_field :picture %>


      <% if current_user %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>

      <p>
        <%= f.submit %>
      </p>
  <% end %>


</div>

app/views/cats/show.html.erb
<%= render 'shared/cat' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if params['controller'] == 'welcome' %>
      home
    <% else %>
      <%= @title %>
    <% end %>
  </title>
  <meta charset="utf-8" />
  <%= stylesheet_link_tag '/assets/bootstrap.min.css', media: 'all' %>
  <%= stylesheet_link_tag '/assets/app.css', media:  'all' %>

  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js' %>
</head>
<body class="<%= "#{controller.controller_name} #{@body_class}".strip %>">
  <div class="container-fluid">
    <%= render "shared/header" %>
    <div class="row">
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="container">
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>

<div class="modal fade" tabindex="-1" role="dialog" id="selCat">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body"></div>
    </div>
  </div>
</div>

<div id="scripts" hidden>
  <%= javascript_include_tag '/assets/bootstrap.min.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</div>
</body>
</html>

app/views/shared/_cat.html.erb
<div class="cat">
  <!--<div>catid <%= @cat.id %></div>-->
  <div><%= @cat.name%></div>
  <div><%= @cat.text %></div>
  <div><%= image_tag @cat.picture %></div>
  <%= @cat.user.name %>
  <div id="like">

    catit
    <!-- /Heart icon -->
    <%= Like::Like.with_likeable(@cat).count %>

    <div>
      <hr/>
      <h6>Users like your cat</h6>
      <% catId(@cat.id).each do |lu| %>
          <strong><%= lu["name"] %></strong>
      <% end %>
      <hr/>
    </div>
  </div>

  <div>
    <% if Like::Like.liking?(@current_user, @cat) %>
        <%= link_to 'Unlike', like_path_for(@cat), method: :delete %>
        <?xml version="1.0" ?>
        <!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
        <svg class="sel" enable-background="new 0 0 128 128" id="" version="1.1" viewBox="0 0 128 128" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <path d="M89.6,14.8c-10.3,0-19.6,4.5-25.6,11.7c-6.3-7.2-15.5-11.7-25.6-11.7C19.5,14.8,4,30.1,4,49.2  C4,60,8.9,69.4,16.6,75.7l0,0l41.2,32.6c3.6,2.9,8.8,2.9,12.4,0l40.3-31.9l0,0c8.3-6.3,13.5-16.2,13.5-27.2  C124,30.3,108.7,14.8,89.6,14.8z" fill="#F37865"/>
          <path d="M19,49.2C19,32.7,30.6,19,45.9,15.6c-2.4-0.5-4.9-0.8-7.5-0.8C19.5,14.8,4,30.1,4,49.2  C4,60,8.9,69.4,16.6,75.7l41.2,32.6c1.8,1.4,4,2.2,6.2,2.2L31.6,75.7C23.5,65.4,19,60,19,49.2z" fill="#FFFFFF"/>
          <path d="M15.7,76.9l41.2,32.6c2,1.6,4.6,2.5,7.1,2.5c0,0,0,0,0,0c2.6,0,5.1-0.9,7.1-2.5l40.3-31.9  c8.9-6.8,14.1-17.1,14.1-28.4c0-19.8-16.1-35.9-35.9-35.9c-9.9,0-19.1,4-25.6,10.9c-6.7-7-15.9-10.9-25.6-10.9  c-19.8,0-35.9,16.1-35.9,35.9C2.5,59.9,7.3,70,15.7,76.9z M38.4,16.3c9.3,0,18.3,4.1,24.5,11.2c0.3,0.3,0.7,0.5,1.1,0.5  c0.4,0,0.9-0.2,1.1-0.5c6-7.1,14.9-11.2,24.5-11.2c18.1,0,32.9,14.8,32.9,32.9c0,10.3-4.7,19.8-12.9,26l-40.3,31.9  c-1.5,1.2-3.4,1.8-5.3,1.8c-1.9,0-3.8-0.7-5.3-1.8L17.5,74.5c-7.7-6.3-12-15.5-12-25.4C5.5,31,20.3,16.3,38.4,16.3z" fill="#62355C"/>
          <path d="M89.6,26.3c12.6,0,22.9,10.3,22.9,22.9c0,0.8,0.7,1.5,1.5,1.5s1.5-0.7,1.5-1.5c0-14.3-11.6-25.9-25.9-25.9  c-0.8,0-1.5,0.7-1.5,1.5S88.8,26.3,89.6,26.3z" fill="#62355C"/>
        </svg>
    <% else %>
        <%= link_to 'Like', like_path_for(@cat), method: :post %>
        <?xml version="1.0" ?>
        <!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
        <svg class="notsel" enable-background="new 0 0 128 128" id="" version="1.1" viewBox="0 0 128 128" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <path d="M89.6,14.8c-10.3,0-19.6,4.5-25.6,11.7c-6.3-7.2-15.5-11.7-25.6-11.7C19.5,14.8,4,30.1,4,49.2  C4,60,8.9,69.4,16.6,75.7l0,0l41.2,32.6c3.6,2.9,8.8,2.9,12.4,0l40.3-31.9l0,0c8.3-6.3,13.5-16.2,13.5-27.2  C124,30.3,108.7,14.8,89.6,14.8z" fill="#F37865"/>
          <path d="M19,49.2C19,32.7,30.6,19,45.9,15.6c-2.4-0.5-4.9-0.8-7.5-0.8C19.5,14.8,4,30.1,4,49.2  C4,60,8.9,69.4,16.6,75.7l41.2,32.6c1.8,1.4,4,2.2,6.2,2.2L31.6,75.7C23.5,65.4,19,60,19,49.2z" fill="#FFFFFF"/>
          <path d="M15.7,76.9l41.2,32.6c2,1.6,4.6,2.5,7.1,2.5c0,0,0,0,0,0c2.6,0,5.1-0.9,7.1-2.5l40.3-31.9  c8.9-6.8,14.1-17.1,14.1-28.4c0-19.8-16.1-35.9-35.9-35.9c-9.9,0-19.1,4-25.6,10.9c-6.7-7-15.9-10.9-25.6-10.9  c-19.8,0-35.9,16.1-35.9,35.9C2.5,59.9,7.3,70,15.7,76.9z M38.4,16.3c9.3,0,18.3,4.1,24.5,11.2c0.3,0.3,0.7,0.5,1.1,0.5  c0.4,0,0.9-0.2,1.1-0.5c6-7.1,14.9-11.2,24.5-11.2c18.1,0,32.9,14.8,32.9,32.9c0,10.3-4.7,19.8-12.9,26l-40.3,31.9  c-1.5,1.2-3.4,1.8-5.3,1.8c-1.9,0-3.8-0.7-5.3-1.8L17.5,74.5c-7.7-6.3-12-15.5-12-25.4C5.5,31,20.3,16.3,38.4,16.3z" fill="#62355C"/>
          <path d="M89.6,26.3c12.6,0,22.9,10.3,22.9,22.9c0,0.8,0.7,1.5,1.5,1.5s1.5-0.7,1.5-1.5c0-14.3-11.6-25.9-25.9-25.9  c-0.8,0-1.5,0.7-1.5,1.5S88.8,26.3,89.6,26.3z" fill="#62355C"/>
        </svg>
    <% end %>
  </div>


</div>

<ul class="list-group-item">
  <% @cat.comments.each do |comment| %>
      <li>
        <strong><%= comment.commenter %></strong>
        <%= comment.body %>
      </li>
  <% end %>
</ul>

<%= form_for([@cat, @cat.comments.build]) do |f| %>
    <%= f.hidden_field :commenter, value: @cur_user.name %>
    <%= f.text_field :body, placeholder: "comment" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_header.html.erb
<div class="row header">
  <div class="container">
    <div class="col-md-12">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">cat</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="/cats/new">new cat</a></li>
            </ul>
            <%= render('shared/search') %>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                  <li>
                    <a href="#">Signed in as <%= current_user.name %></a>
                  </li>
                  <li><%= link_to "Logout", '/logout' %></li>
              <% else %>
                  <li><%= link_to 'Login', '/login' %></li>
                  <li><%= link_to 'Signup', '/signup' %></li>
              <% end %>

            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>
  </div>
</div>

app/views/shared/_heart_svg.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 20.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg width="16" version="1.1" id="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 130 105" style="enable-background:new 0 0 130 105;" xml:space="preserve">
  <path class="st0" d="M90.6,4.8C80.3,4.8,71,9.3,65,16.5C58.7,9.3,49.5,4.8,39.4,4.8C20.5,4.8,5,20.1,5,39.2C5,50,9.9,59.4,17.6,65.7 l0,0l41.2,32.6c3.6,2.9,8.8,2.9,12.4,0l40.3-31.9l0,0c8.3-6.3,13.5-16.2,13.5-27.2C125,20.3,109.7,4.8,90.6,4.8z"/>
  <path class="st1" d="M65,101.5c-2.4,0-4.8-0.9-6.8-2.4L17,66.5C8.7,59.7,4,49.8,4,39.2C4,19.7,19.9,3.8,39.4,3.8 c2.5,0,5.1,0.3,7.7,0.8l0,2C32,9.9,21,23.7,21,39.2c0,10.1,4.2,15.4,11.7,25l0.7,0.9l33.9,36.4H65z"/>
  <path class="st1" d="M33,40.1C33,24,43.8,10.6,58,7.2c-2.2-0.5-4.5-0.8-7-0.8c-17.5,0-31.9,15-31.9,33.7c0,10.6,4.5,19.8,11.7,25.9 L69,98c1.7,1.4,3.7,2.2,5.8,2.2L44.7,66.1C37.2,56,33,50.7,33,40.1z"/>
  <path class="st1" d="M41.2,39.9c2.1-13.7,11.7-24.2,23.6-27.7c1.5-0.4,1.4-2.6-0.1-2.8c-0.2,0-0.4-0.1-0.6-0.1 c-17.3-2.6-33.8,10-36.6,28.5c-1.6,10.5,1.5,20.2,7.7,27.4l18.7,26.3l7.2,12.2l7.1-1.2c0,0,0,0,0,0c1.2,1.3,3.2-0.3,2.3-1.8 L48.9,67.4c0,0,0-0.1-0.1-0.1C42.9,56.2,39.6,50.4,41.2,39.9z"/>
  <path class="st1" d="M39.2,37.1c4.2-11,15.7-17.5,28.4-17.4c1.6,0,1.8-1.8,0.3-2.4c-0.2-0.1-0.4-0.2-0.6-0.2 c-17.5-6.6-36.4-0.1-42,14.8c-3.2,8.4-1.4,17.5,3.9,25.1l15.5,26.9L50.3,96l7.5,0.8c0,0,0,0,0,0.1c1,1.4,3.4,0.5,2.6-0.9L43.1,62.2 c0,0,0-0.1,0-0.1C38.6,51.3,36,45.5,39.2,37.1z"/>
  <path class="st2" d="M65,105c-3.2,0-6.5-1.2-9-3.2L14.8,69.3C5.7,61.8,0.5,50.8,0.5,39.2C0.5,17.8,18,0.3,39.4,0.3 C49,0.3,58,3.7,65,10c6.9-6.2,16.1-9.7,25.6-9.7c21.5,0,38.9,17.5,38.9,38.9c0,12.1-5.6,23.4-15.3,30.8L74,101.9 C71.4,103.9,68.2,105,65,105z M39.4,9.3C22.9,9.3,9.5,22.7,9.5,39.1c0,9,4,17.4,10.9,23.1l41.2,32.6c1,0.7,2.3,1.2,3.4,1.2 c1.3,0,2.5-0.4,3.4-1.1l40.3-31.9c7.5-5.7,11.8-14.3,11.8-23.6c0-16.5-13.4-29.9-29.9-29.9C82,9.3,73.9,13,68.5,19.4 C67.5,20.6,66,21,65,21c-1.2,0-2.3-0.5-3.2-1.4l-0.1-0.1C56,13,47.9,9.3,39.4,9.3z"/>
  <path class="st2" d="M65,103c-2.7,0-5.6-1-7.7-2.7L16.1,67.7C7.4,60.6,2.5,50.2,2.5,39.2c0-20.3,16.6-36.9,36.9-36.9 C49.1,2.3,58.2,6,65,12.8C71.7,6.1,80.9,2.3,90.6,2.3c20.3,0,36.9,16.6,36.9,36.9c0,11.5-5.3,22.2-14.5,29.2l-40.3,31.9 C70.5,102,67.8,103,65,103z M39.4,7.3C21.8,7.3,7.5,21.6,7.5,39.1c0,9.6,4.2,18.6,11.6,24.6l41.2,32.6c1.4,1,3.1,1.6,4.7,1.6 c1.7,0,3.4-0.6,4.7-1.6L110,64.4c8-6,12.5-15.2,12.5-25.2c0-17.6-14.3-31.9-31.9-31.9c-9.2,0-17.9,3.9-23.7,10.8 C66.4,18.7,65.6,19,65,19c-0.6,0-1.3-0.3-1.8-0.8C57.1,11.3,48.5,7.3,39.4,7.3z"/>
  <path class="st2" d="M102.3,51c-2.2,0-4.1-1.9-4.1-4.1c0-7.3-8.1-18.1-18.1-18.1c-2.2,0-4.1-1.9-4.1-4.1s1.9-4.1,4.1-4.1 c14.5,0,26.3,11.8,26.3,26.3C106.4,49.1,104.5,51,102.3,51z"/>
</svg>

app/views/shared/_search.html.erb
<%= form_tag(cats_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search Cats", class: "form-control" %>
    </div>
    <div id="search_result">

    </div>
  <!--<%= submit_tag "Search", class:'btn btn-default' %>-->
<% end %>
<script>
  $(function () {
    $('#search').on('keyup', function () {
      var t = $(this).val();
      var postData = $(this).serializeArray();
      $.ajax({
        url: '/cats',
        type: 'GET',
        data: postData,
        success: function (data) {

          $response=$(data);
          //$raw = $response.find('#sR').html();
          debugger
          //$('#search_result').html($raw)
        },
        timeout: 3000
      });
    });
  });

//  $.get('movies.html', function (response) {
//    var source = $(response);
//    $('#movies').html(source.find('#action-container').html());
//  });
</script>

<div hidden="" id="sR">
  <% if @catFind.present? %>
      <%= render 'shared/search_result' %>
  <% else %>
      <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>

app/views/shared/_search_result.html.erb
  <% @catFind.each do |catFind| %>
      <%= catFind.name %>
      <%= catFind.text %>
      <%= image_tag catFind.picture.url %>
      <%= link_to 'Show', cat_path(catFind) %>
      <%= Like::Like.with_likeable(catFind).count %>
  <% end %>

app/views/users/show.html.erb
<% @title = "catogramm" %>
<div class="col-md-12">

  <%= gravatar_for @user%>
  <%= @user.name %><br/>
  <%= @user.nickname %><br/>
  <%= @user.website %><br/>
  <%= @user.about %><br/>
  <%= @user.phone %><br/>
  <%= @user.sex %><br/>



  <% @users_cats.each do |usersCat| %>
      <%= usersCat.name %><br/>
      <div><%= image_tag usersCat.picture.url(:thumb) %></div>
  <% end %>

  <% if current_user %>
    <%= link_to 'edit profile', edit_user_path %>
  <% else %>
    <%#= link_to 'Like', edit_user_path %>
  <% end %>

  <div>
    have <%= @users_cats_count %> cats<br/>
  </div>
</div>